<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XIPL0401" ignored="0" name="Test" tests="12" failures="1" timestamp="07 Aug 2019 10:35:11 GMT" time="8.019" errors="0">
  <testcase name="checkContentType" time="0.006" classname="com.employeeapi.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkResponBody" time="0.033" classname="com.employeeapi.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employeeapi.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkContentType" time="0.003" classname="com.employeeapi.testCases.TC003_Post_EmployeeRecord"/>
  <testcase name="checkResponBody" time="0.004" classname="com.employeeapi.testCases.TC003_Post_EmployeeRecord"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employeeapi.testCases.TC003_Post_EmployeeRecord"/>
  <testcase name="checkResponBody" time="0.004" classname="com.employeeapi.testCases.TC004_Put_EmployeeRecord"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employeeapi.testCases.TC004_Put_EmployeeRecord"/>
  <testcase name="checkResponBody" time="0.003" classname="com.employeeapi.testCases.TC005_Delete_EmployeeRecord">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testCases.TC005_Delete_EmployeeRecord.checkResponBody(TC005_Delete_EmployeeRecord.java:41)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkResponBody -->
  <testcase name="checkContentType" time="0.002" classname="com.employeeapi.testCases.TC002_Get_Single_EmployeeRecord"/>
  <testcase name="checkResponBody" time="0.003" classname="com.employeeapi.testCases.TC002_Get_Single_EmployeeRecord"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employeeapi.testCases.TC002_Get_Single_EmployeeRecord"/>
</testsuite> <!-- Test -->
